apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendation
  namespace: ecommerce
spec:
  hosts:
    - recommendation
  http:
  - route:
    - destination:
        host: recommendation
        subset: v6
      weight: 50
    - destination:
        host: recommendation
        subset: v7
      weight: 50