apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-v1
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
        version: v1
    spec:
      containers:
      - name: review
        image: hiprabhat/ecommerce-review:v1
        imagePullPolicy: Always
        env:
        - name: PERSON_SERVICE_URL
          value: http://person.ecommerce.svc.cluster.local/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
