apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: review
spec:
  host: review
  subsets:
  - name: v6
    labels:
      version: v6
  - name: v7
    labels:
      version: v7