apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: review
  namespace: ecommerce
spec:
  hosts:
    - review
  http:
  - route:
    - destination:
        host: review
        subset: v1
      weight: 50
    - destination:
        host: review
        subset: v2
      weight: 50
