apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: hiprabhat/ecommerce-product:v1
        imagePullPolicy: Always
        env:
        - name: REVIEW_SERVICE_URL
          value: http://review.ecommerce.svc.cluster.local/
        - name: RECOMMENDATION_SERVICE_URL
          value: http://recommendation.ecommerce.svc.cluster.local/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: ecommerce
  labels:
    app: product
spec:
  selector:
    app: product
  ports:
  - port: 80
    targetPort: 8082
    name: http-product
